package resolver

import (
	"fmt"
	"net/netip"
	"strings"
)

// The guest side of ADR 0008. The host resolver cannot listen on port 53:
// that needs root on the host, and jm is not a privileged tool. The guest
// therefore runs the one hop that turns "port 53, as libc insists" into
// "the port the host resolver actually bound": local_unbound, which is in
// the FreeBSD base system, configured as a pure forwarder to the host
// resolver through the provider's host alias.
//
// Everything in the guest then has exactly one nameserver — the guest's own
// address, which containers can reach as well as the guest itself — and
// every query it receives is answered by the host (ADR 0008: the guest is
// given the provider's resolver and nothing else).

// Guest-side paths.
const (
	GuestUnboundConf    = "/var/unbound/unbound.conf"
	GuestResolvConf     = "/etc/resolv.conf"
	GuestResolvconfConf = "/etc/resolvconf.conf"
	GuestService        = "local_unbound"
	// GuestContainersConfDir is the engine's configuration drop-in
	// directory in the guest, and GuestContainersConf the file jm owns in
	// it. GuestEngineService is restarted when it changes.
	GuestContainersConfDir = "/usr/local/etc/containers/containers.conf.d"
	GuestContainersConf    = GuestContainersConfDir + "/50-jailmachine-dns.conf"
	GuestEngineService     = "podman_service"
	GuestEngineSocket      = "/var/run/podman/podman.sock"
	// GuestDaemon is the process name behind GuestService.
	GuestDaemon = "local-unbound"
	// generatedTag marks a guest file as jm's own. It is what tells a
	// guest whose resolution jm has already taken over from one still
	// using whatever it booted with, which is the difference between a
	// failed start and a warning (ADR 0008).
	generatedTag = "Generated by jailmachine (jm)"
)

// generatedHeader heads every guest file this package renders.
const generatedHeader = "# " + generatedTag + "; ADR 0008, name resolution parity.\n"

// OwnsResolvConfCmd is the shell test that jm already owns the guest's
// /etc/resolv.conf. A guest that answers yes has no earlier resolution to
// fall back on, so a resolver that will not come up there is a broken
// machine rather than a machine without parity.
func OwnsResolvConfCmd() string {
	return fmt.Sprintf("grep -q %s %s", shellSingleQuote(generatedTag), GuestResolvConf)
}

// GuestConfig is what the guest needs to know to route its DNS to the host
// resolver.
type GuestConfig struct {
	// UpstreamIP and UpstreamPort are where the host resolver is reachable
	// from inside the guest network (the provider's host alias and the
	// port the resolver bound on the host's loopback).
	UpstreamIP   string
	UpstreamPort int
	// Nameserver is the address the guest and its containers send queries
	// to: the guest's own address on the provider's network, so that a
	// container's copy of /etc/resolv.conf works from its own namespace.
	Nameserver string
	// HostAlias is the address that means "the host" inside the guest
	// network. The container engine is told to use it for the
	// host.containers.internal / host.docker.internal entries it writes
	// into every container's hosts file, which otherwise name the guest:
	// in a machine, "the host" is the user's own computer, not the VM
	// (ADR 0008).
	HostAlias string
	// Search is the host's effective search list, most specific first.
	Search []string
}

// Validate rejects a configuration that would produce a broken or unsafe
// guest file; every value ends up in a configuration file in the guest.
func (g GuestConfig) Validate() error {
	if _, err := netip.ParseAddr(g.UpstreamIP); err != nil {
		return fmt.Errorf("resolver: bad upstream address %q: %w", g.UpstreamIP, err)
	}
	if g.UpstreamPort < 1 || g.UpstreamPort > 65535 {
		return fmt.Errorf("resolver: bad upstream port %d", g.UpstreamPort)
	}
	if _, err := netip.ParseAddr(g.Nameserver); err != nil {
		return fmt.Errorf("resolver: bad nameserver address %q: %w", g.Nameserver, err)
	}
	if _, err := netip.ParseAddr(g.HostAlias); err != nil {
		return fmt.Errorf("resolver: bad host alias %q: %w", g.HostAlias, err)
	}
	for _, d := range g.Search {
		if !plausibleDomain(d) {
			return fmt.Errorf("resolver: bad search domain %q", d)
		}
	}
	return nil
}

// specialUseZones are the RFC 6761 special-use TLDs unbound answers locally
// unless told otherwise. Each one is a name the host may well resolve — from
// /etc/hosts, a VPN resolver or a local proxy — so each must reach the host
// resolver instead (ADR 0008).
var specialUseZones = []string{"test.", "invalid.", "home.arpa.", "onion."}

// UnboundConf renders the guest's unbound configuration: a forwarder with
// no cache and no opinions of its own, so that what the guest sees is what
// the host answered, when it answered it.
func (g GuestConfig) UnboundConf() string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# Every query is forwarded to the host resolver, which answers through\n")
	b.WriteString("# the host operating system's own resolution API. Do not edit: jm start\n")
	b.WriteString("# rewrites this file, and the upstream port changes between runs.\n")
	b.WriteString("server:\n")
	b.WriteString("\tverbosity: 0\n")
	b.WriteString("\tusername: unbound\n")
	b.WriteString("\tdirectory: \"/var/unbound\"\n")
	b.WriteString("\tchroot: \"\"\n")
	b.WriteString("\tpidfile: \"/var/run/local_unbound.pid\"\n")
	b.WriteString("\tport: 53\n")
	// Bound to named addresses rather than the wildcard: a wildcard socket
	// answers a container from whichever address the route to it picks
	// (the container bridge), and a reply from an address the query did
	// not go to is dropped by the client as a spoof.
	b.WriteString("\tinterface: 127.0.0.1\n")
	fmt.Fprintf(&b, "\tinterface: %s\n", g.Nameserver)
	// Containers query from the engine's own subnets, which the guest
	// alone can reach; nothing outside the machine can.
	b.WriteString("\taccess-control: 0.0.0.0/0 allow\n")
	b.WriteString("\tdo-ip6: no\n")
	// No validator: the host resolver is the authority here, and a
	// split-horizon answer has no signature to check.
	b.WriteString("\tmodule-config: \"iterator\"\n")
	// The host's answer is only true at the time of asking (ADR 0008).
	b.WriteString("\tcache-max-ttl: 0\n")
	b.WriteString("\tcache-max-negative-ttl: 0\n")
	b.WriteString("\tprefetch: no\n")
	b.WriteString("\tqname-minimisation: no\n")
	// Private, link-local and multicast names must reach the host instead
	// of unbound's built-in "this cannot exist" answers.
	b.WriteString("\tunblock-lan-zones: yes\n")
	b.WriteString("\tinsecure-lan-zones: yes\n")
	b.WriteString("\tdomain-insecure: \".\"\n")
	b.WriteString("\tlocal-zone: \"local.\" nodefault\n")
	b.WriteString("\tlocal-zone: \"254.169.in-addr.arpa.\" nodefault\n")
	// The RFC 6761 special-use names unbound blackholes by default. ".test"
	// in particular is the standard local-development TLD (Valet, puma-dev,
	// dinghy), and a developer who put one in /etc/hosts must get the
	// host's answer here rather than unbound's NXDOMAIN (ADR 0008).
	// "localhost." is deliberately NOT in this list: unbound's built-in
	// loopback answer must stand, or the host's 127.0.0.1 would be
	// rewritten to the host alias and "localhost" would mean the Mac.
	for _, zone := range specialUseZones {
		fmt.Fprintf(&b, "\tlocal-zone: %q nodefault\n", zone)
	}
	b.WriteString("\thide-identity: yes\n")
	b.WriteString("\thide-version: yes\n")
	b.WriteString("forward-zone:\n")
	b.WriteString("\tname: \".\"\n")
	fmt.Fprintf(&b, "\tforward-addr: %s@%d\n", g.UpstreamIP, g.UpstreamPort)
	return b.String()
}

// ContainersConf renders the engine drop-in that makes a container's
// host.containers.internal entry point at the user's computer.
func (g GuestConfig) ContainersConf() string {
	return generatedHeader +
		"[containers]\n" +
		fmt.Sprintf("host_containers_internal_ip = %q\n", g.HostAlias)
}

// ResolvConf renders the guest's /etc/resolv.conf: the host's search list,
// and exactly one nameserver.
func (g GuestConfig) ResolvConf() string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# The single nameserver forwards every query to the host resolver.\n")
	if len(g.Search) > 0 {
		fmt.Fprintf(&b, "search %s\n", strings.Join(g.Search, " "))
	}
	fmt.Fprintf(&b, "nameserver %s\n", g.Nameserver)
	return b.String()
}

// Script renders the idempotent /bin/sh program that applies the
// configuration in the guest. It rewrites a file only when its contents
// change, and restarts the forwarder only when its configuration did, so
// that a "jm start" on a running machine costs nothing and does not break
// name resolution for containers that are already up.
func (g GuestConfig) Script() (string, error) {
	if err := g.Validate(); err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("set -e\numask 022\nchanged=no\nengine_changed=no\nmkdir -p /var/unbound\n")
	writeFile(&b, "JM_UNBOUND", GuestUnboundConf, g.UnboundConf(), "changed=yes")
	fmt.Fprintf(&b, "sysrc %s_enable=YES >/dev/null\n", GuestService)
	// "service restart" races with a forwarder that takes a moment to go
	// away and then refuses to start over itself, so stop, wait for the
	// process, and start. Nothing here is fatal: the probe below decides
	// whether the guest really resolves.
	fmt.Fprintf(&b, "if [ \"$changed\" = yes ] || ! service %s status >/dev/null 2>&1; then\n", GuestService)
	fmt.Fprintf(&b, "\tservice %s stop >/dev/null 2>&1 || true\n", GuestService)
	fmt.Fprintf(&b, "\ti=0\n\twhile [ $i -lt 15 ] && pgrep -qx %s >/dev/null 2>&1; do sleep 1; i=$((i+1)); done\n", GuestDaemon)
	fmt.Fprintf(&b, "\tpkill -9 -x %s >/dev/null 2>&1 || true\n", GuestDaemon)
	fmt.Fprintf(&b, "\tservice %s start >/dev/null 2>&1 || true\n", GuestService)
	b.WriteString("fi\n")
	// Nothing below runs until the forwarder answers: /etc/resolv.conf is
	// only taken over by a resolver that works, so a failure here leaves
	// the guest with the name resolution it already had.
	b.WriteString("i=0\n")
	fmt.Fprintf(&b, "while [ $i -lt 20 ] && ! %s; do sleep 1; i=$((i+1)); done\n", probe)
	fmt.Fprintf(&b, "%s\n", probe)
	// resolvconf(8) rewrites /etc/resolv.conf on every DHCP event and would
	// put the provider's DHCP nameserver back; the guest must have ours and
	// only ours (ADR 0008).
	fmt.Fprintf(&b, "if [ ! -f %s ] || ! grep -q '^resolv_conf=' %s; then\n", GuestResolvconfConf, GuestResolvconfConf)
	fmt.Fprintf(&b, "\techo 'resolv_conf=\"/dev/null\" # jailmachine owns %s' >> %s\n", GuestResolvConf, GuestResolvconfConf)
	b.WriteString("fi\n")
	writeFile(&b, "JM_RESOLV", GuestResolvConf, g.ResolvConf(), "")
	fmt.Fprintf(&b, "chmod 644 %s\n", GuestResolvConf)
	// The engine writes host.containers.internal into every container's
	// hosts file, where it shadows DNS; left alone it names the guest.
	fmt.Fprintf(&b, "mkdir -p %s\n", GuestContainersConfDir)
	writeFile(&b, "JM_CONTAINERS", GuestContainersConf, g.ContainersConf(), "engine_changed=yes")
	b.WriteString("if [ \"$engine_changed\" = yes ]; then\n")
	fmt.Fprintf(&b, "\tservice %s status >/dev/null 2>&1 && service %s restart >/dev/null 2>&1 || true\n",
		GuestEngineService, GuestEngineService)
	fmt.Fprintf(&b, "\ti=0\n\twhile [ $i -lt 30 ] && [ ! -S %s ]; do sleep 1; i=$((i+1)); done\n", GuestEngineSocket)
	b.WriteString("fi\n")
	return b.String(), nil
}

// probe is the shell test that the guest's forwarder answers at all: the
// host alias is answered by the host resolver itself, so a reply means the
// whole path is up.
var probe = fmt.Sprintf("host -W 2 -t A %s 127.0.0.1 >/dev/null 2>&1", ProbeName)

// ProbeName is the name used to check that the guest's resolver answers.
const ProbeName = "host.containers.internal"

// writeFile appends the shell that installs content at path only when it
// differs from what is there, running onChange when it did.
func writeFile(b *strings.Builder, marker, path, content, onChange string) {
	fmt.Fprintf(b, "cat > %s.jm <<'%s_EOF'\n%s%s_EOF\n", path, marker, content, marker)
	fmt.Fprintf(b, "if cmp -s %s.jm %s; then\n\trm -f %s.jm\nelse\n\tmv %s.jm %s\n", path, path, path, path, path)
	if onChange != "" {
		fmt.Fprintf(b, "\t%s\n", onChange)
	}
	b.WriteString("fi\n")
}

// VerifyCommand is a shell command that resolves name through server (the
// guest's nameserver, the same address containers are given) and prints the
// addresses it got, one per line. It is how "jm start" and "jm doctor"
// assert that parity really holds in the guest rather than that a daemon
// happens to be running (ADR 0008).
func VerifyCommand(name, server string) string {
	return fmt.Sprintf("host -W 5 -t A %s %s 2>&1 | awk '/has address/ {print $NF}'",
		shellSingleQuote(name), shellSingleQuote(server))
}

// shellSingleQuote quotes s for /bin/sh.
func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
