#!/bin/sh
# first-boot provisioning, run by nuageinit as root
# Expects JM_SSH_PUBKEY and JM_HOSTNAME in the environment (the seed builder
# prepends "JM_SSH_PUBKEY='...'" / "JM_HOSTNAME='...'" lines to this file).
exec > /var/log/jm-provision.log 2>&1
set -ex
# Any failure leaves a failure marker (jm start reads it) and no ready marker.
trap 'rc=$?; [ $rc -eq 0 ] || { echo "jm-provision: FAILED (exit $rc)"; touch /var/db/jm-provision-failed; }' EXIT
: "${JM_HOSTNAME:=jailmachine}"
[ -n "${JM_SSH_PUBKEY:-}" ] || { echo "JM_SSH_PUBKEY not set" >&2; exit 1; }
sysrc hostname="$JM_HOSTNAME"; hostname "$JM_HOSTNAME"
mkdir -p /root/.ssh; chmod 700 /root/.ssh
echo "$JM_SSH_PUBKEY" > /root/.ssh/authorized_keys; chmod 600 /root/.ssh/authorized_keys
sysrc sshd_enable=YES
sed -i '' -e 's/^#\{0,1\}PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config
# On first boot sshd has never run, so "restart" fails its config test with
# "No host key files found" (keys are generated by the start precmd): make the
# keys first, and fall back to start if restart still fails.
service sshd keygen
service sshd restart || service sshd start
# Fast path (ADR 0003, docs/guest-contract.md): a prebaked image built by
# "jm image build" already ran everything below and carries the ready
# marker; its seal.sh put /firstboot back so this script runs once more on
# the new machine. Only the per-machine bits above are needed, plus making
# sure the services are up. Nothing else may run here: the slow path is
# the single source of truth and the image is built by running it.
if [ -f /var/db/jm-provisioned ]; then
  echo "jm-provision: prebaked image, fast path"
  sysrc zfs_enable=YES linux_enable=YES pf_enable=YES podman_service_enable=YES podman_enable=YES bastille_enable=YES
  service zfs start || true
  service linux start || true
  service pf status >/dev/null 2>&1 || service pf start
  service podman_service status >/dev/null 2>&1 || service podman_service start
  i=0; until [ -S /var/run/podman/podman.sock ] || [ $i -ge 30 ]; do sleep 1; i=$((i+1)); done
  [ -S /var/run/podman/podman.sock ]
  exit 0
fi
# The official (pkgbase) cloud image upgrades base on first boot via
# firstboot_pkg_upgrade, which runs before this script (rcorder 115 vs 158)
# and may install a new kernel and request a reboot (/firstboot-reboot). That
# reboot must not fire mid-way through this script (nuageinit never re-runs),
# so it is cancelled here; the script still waits in case pkg is running.
# jm start compares "freebsd-version -k" with "-r" once the ready marker is
# there and reboots the guest itself when they differ, so the new kernel
# (and its linux64/linprocfs modules) is in use before podman is connected.
sysrc firstboot_pkg_upgrade_enable=NO || true
i=0; while pgrep -qf firstboot_pkg_upgrade || pgrep -qx pkg || pgrep -qx pkg-static; do
  [ $i -ge 600 ] && { echo "first-boot pkg upgrade still running after 20 min" >&2; exit 1; }
  sleep 2; i=$((i+1))
done
rm -f /firstboot-reboot
# nuageinit runs before DHCP has finished: wait for DNS
i=0; until host -W 2 pkg.freebsd.org >/dev/null 2>&1 || [ $i -ge 60 ]; do sleep 2; i=$((i+1)); done
# packages
env ASSUME_ALWAYS_YES=yes pkg bootstrap -f
pkg install -y podman-suite bastille
# zfs / storage for containers
sysrc zfs_enable=YES
zfs create -o mountpoint=/var/db/containers zroot/containers || true
# linuxulator. "service linux start" exits 0 even when kldload fails, so
# assert the modules podman's --os=linux containers need are really loaded.
# When the on-disk kernel differs from the running one (firstboot_pkg_upgrade
# installed a new kernel), the modules cannot load until the reboot jm start
# performs, so only warn in that case.
sysrc linux_enable=YES; service linux start || true
if [ "$(freebsd-version -k)" = "$(freebsd-version -r)" ]; then
  # -n checks by file name: the module inside linux64.ko is linux64elf on arm64.
  kldstat -q -n linux64 && kldstat -q -m linprocfs
else
  echo "kernel on disk ($(freebsd-version -k)) != running ($(freebsd-version -r)): linuxulator loads after the reboot jm start performs"
fi
# pf (nat for containers), per podman pkg message
ext_if=$(route -n get default | awk '/interface:/{print $2}')
sed -E "s/^(v[46]egress_if) = \"[^\"]*\"/\1 = \"$ext_if\"/" /usr/local/etc/containers/pf.conf.sample > /etc/pf.conf
sysrc pf_enable=YES; service pf start
# podman REST API on a unix socket (the stock 'podman' rc script only restarts containers)
cat > /usr/local/etc/rc.d/podman_service <<'RC'
#!/bin/sh
# PROVIDE: podman_service
# REQUIRE: LOGIN pf
# KEYWORD: shutdown
. /etc/rc.subr
name=podman_service
rcvar=podman_service_enable
: ${podman_service_enable:=NO}
: ${podman_service_socket:="unix:///var/run/podman/podman.sock"}
pidfile=/var/run/podman_service.pid
command=/usr/sbin/daemon
command_args="-f -P ${pidfile} -o /var/log/podman_service.log /usr/local/bin/podman system service --time=0 ${podman_service_socket}"
start_precmd="mkdir -p /var/run/podman"
load_rc_config $name
run_rc_command "$1"
RC
chmod +x /usr/local/etc/rc.d/podman_service
sysrc podman_service_enable=YES; service podman_service start
# ports' own rc script restarts containers with restart-policy=always after a reboot
sysrc podman_enable=YES
# wait for the API socket; jm start checks for it before declaring ready
i=0; until [ -S /var/run/podman/podman.sock ] || [ $i -ge 30 ]; do sleep 1; i=$((i+1)); done
[ -S /var/run/podman/podman.sock ]
# bastille; its rc script complains until the jails directory exists
sysrc bastille_enable=YES
mkdir -p /usr/local/bastille/jails
# bastille on a ZFS host needs its zfs settings, a loopback for jail IPs, and NAT.
# We do NOT run 'bastille setup pf': it would overwrite podman's pf.conf.
sysrc -f /usr/local/etc/bastille/bastille.conf bastille_zfs_enable=YES bastille_zfs_zpool=zroot
sysrc cloned_interfaces+=lo1 ifconfig_lo1_name=bastille0
service netif cloneup || true
grep -q 'table <jails>' /etc/pf.conf || printf '\n# bastille jails\ntable <jails> persist\nnat on $v4egress_if inet from <jails> to any -> ($v4egress_if)\nrdr-anchor "rdr/*"\n' >> /etc/pf.conf
pfctl -nf /etc/pf.conf && service pf reload
rm -f /var/db/jm-provision-failed
touch /var/db/jm-provisioned
